FROM node:12.18.4-alpine as client

WORKDIR /app

ENV PATH/app/node_modules/.bin:$PATH

COPY ./package*.json /app/

RUN npm install --silent

RUN npm install react-scripts -g --silent

COPY . .

RUN npm build

FROM nginx:latest

EXPOSE 3000


COPY --from=client/app/build/var/www/html



CMD ['node','insex.jsx']